# Generated by Django 4.2.5 on 2024-09-28 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_images', models.ImageField(upload_to='')),
                ('paper_names', models.CharField(max_length=100)),
                ('paper_disc', models.TextField(max_length=500)),
                ('paper_notes', models.ImageField(upload_to='')),
                ('paper_time', models.TimeField(default=django.utils.timezone.now)),
                ('paper_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
