# Generated by Django 4.2.5 on 2024-09-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_models',
            name='paper_notes',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
