# Generated by Django 4.2.5 on 2024-09-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Papers', '0002_alter_paper_models_paper_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_models',
            name='paper_notes',
        ),
    ]
