# Generated by Django 4.2.5 on 2024-09-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papers', '0003_remove_paper_models_paper_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_models',
            name='paper_categorys',
            field=models.CharField(default='', max_length=50),
        ),
    ]
