# Generated by Django 4.2.5 on 2024-09-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papers', '0004_paper_models_paper_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_models',
            name='paper_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
