# Generated by Django 4.2.5 on 2024-09-30 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Papers', '0006_paper_models_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_images', models.ImageField(upload_to='')),
                ('user_name', models.CharField(max_length=100)),
                ('note_names', models.CharField(max_length=100)),
                ('note_title', models.CharField(max_length=200)),
                ('note_categorys', models.CharField(max_length=50)),
                ('note_desc', models.TextField(max_length=500)),
                ('note_time', models.TimeField(default=django.utils.timezone.now)),
                ('note_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
